language: python
python:
  - 2.7
  - 2.6
addons:
  apt:
    packages:
      - gcc
      - python-dev
install:
  - pip install -U pip
  - pip install coveralls
  - pip install -r requirements-dev.txt
script:
  - py.test --cov . --cov-report term-missing --ignore config-template.py
after_success:
  - coveralls
matrix:
  allow_failures:
    - python: 2.6
sudo: false